/////////////////////////////////////////////////////////////////////
//                                                                 //
// This Integer test file is auto-generated by "script/lib-gen.sh" //
//                                                                 //
/////////////////////////////////////////////////////////////////////

import Integer from "../lib/Integer";
import { Equal, Expect } from "../utils";

type CaseLibInteger = [
  // Integer.Add
  Expect<Equal<Integer.Add<2, 3>, 5>>,
  Expect<Equal<Integer.Add<-2, 2>, 0>>,
  Expect<Equal<Integer.Add<-2, -6>, -8>>,
  Expect<Equal<Integer.Add<3, -3>, 0>>,
  Expect<Equal<Integer.Add<3, -2>, 1>>,
  Expect<Equal<Integer.Add<-2, 1>, -1>>,
  Expect<Equal<Integer.Add<0, 0>, 0>>,
  Expect<Equal<Integer.Add<-2, 0>, -2>>,
  Expect<Equal<Integer.Add<2, 0>, 2>>,
  Expect<Equal<Integer.Add<0, 20>, 20>>,
  Expect<Equal<Integer.Add<0, -30>, -30>>,

  // Integer.IsPositive
  Expect<Equal<Integer.IsPositive<-2>, false>>,
  Expect<Equal<Integer.IsPositive<0>, false>>,
  Expect<Equal<Integer.IsPositive<9>, true>>,

  // Integer.IsNegative
  Expect<Equal<Integer.IsNegative<-2>, true>>,
  Expect<Equal<Integer.IsNegative<0>, false>>,
  Expect<Equal<Integer.IsNegative<9>, false>>,

  // Integer.Great
  Expect<Equal<Integer.Great<2, 1>, true>>,
  Expect<Equal<Integer.Great<1, 2>, false>>,
  Expect<Equal<Integer.Great<2, -1>, true>>,
  Expect<Equal<Integer.Great<-1, 2>, false>>,
  Expect<Equal<Integer.Great<-3, -2>, false>>,
  Expect<Equal<Integer.Great<-2, -3>, true>>,
  Expect<Equal<Integer.Great<-1, 0>, false>>,
  Expect<Equal<Integer.Great<2, 0>, true>>,
  Expect<Equal<Integer.Great<0, 3>, false>>,
  Expect<Equal<Integer.Great<0, -3>, true>>,
  Expect<Equal<Integer.Great<0, 0>, false>>,
  Expect<Equal<Integer.Great<2, 2>, false>>,
  Expect<Equal<Integer.Great<-2, -2>, false>>,

  // Integer.IsZero
  Expect<Equal<Integer.IsZero<-2>, false>>,
  Expect<Equal<Integer.IsZero<0>, true>>,
  Expect<Equal<Integer.IsZero<9>, false>>,

  // Integer.Sub
  Expect<Equal<Integer.Sub<2, 3>, -1>>,
  Expect<Equal<Integer.Sub<3, 2>, 1>>,
  Expect<Equal<Integer.Sub<-2, 3>, -5>>,
  Expect<Equal<Integer.Sub<-2, -3>, 1>>,
  Expect<Equal<Integer.Sub<-9, -2>, -7>>,
  Expect<Equal<Integer.Sub<2, 0>, 2>>,
  Expect<Equal<Integer.Sub<-3, 0>, -3>>,
  Expect<Equal<Integer.Sub<0, 2>, -2>>,
  Expect<Equal<Integer.Sub<0, -3>, 3>>,
  Expect<Equal<Integer.Sub<0, 0>, 0>>,
  Expect<Equal<Integer.Sub<2, 2>, 0>>,
  Expect<Equal<Integer.Sub<-3, -3>, 0>>,

  // Integer.Less
  Expect<Equal<Integer.Less<2, 1>, false>>,
  Expect<Equal<Integer.Less<1, 2>, true>>,
  Expect<Equal<Integer.Less<2, -1>, false>>,
  Expect<Equal<Integer.Less<-1, 2>, true>>,
  Expect<Equal<Integer.Less<-3, -2>, true>>,
  Expect<Equal<Integer.Less<-2, -3>, false>>,
  Expect<Equal<Integer.Less<-1, 0>, true>>,
  Expect<Equal<Integer.Less<2, 0>, false>>,
  Expect<Equal<Integer.Less<0, 3>, true>>,
  Expect<Equal<Integer.Less<0, -3>, false>>,
  Expect<Equal<Integer.Less<0, 0>, false>>,
  Expect<Equal<Integer.Less<2, 2>, false>>,
  Expect<Equal<Integer.Less<-2, -2>, false>>,

  // Integer.Opposite
  Expect<Equal<Integer.Opposite<-2>, 2>>,
  Expect<Equal<Integer.Opposite<0>, 0>>,
  Expect<Equal<Integer.Opposite<20>, -20>>,

  // Integer.Inc
  Expect<Equal<Integer.Inc<2>, 3>>,
  Expect<Equal<Integer.Inc<0>, 1>>,
  Expect<Equal<Integer.Inc<-1>, 0>>,
  Expect<Equal<Integer.Inc<-30>, -29>>,

  // Integer.GreatEq
  Expect<Equal<Integer.GreatEq<2, 1>, true>>,
  Expect<Equal<Integer.GreatEq<1, 2>, false>>,
  Expect<Equal<Integer.GreatEq<2, -1>, true>>,
  Expect<Equal<Integer.GreatEq<-1, 2>, false>>,
  Expect<Equal<Integer.GreatEq<-3, -2>, false>>,
  Expect<Equal<Integer.GreatEq<-2, -3>, true>>,
  Expect<Equal<Integer.GreatEq<-1, 0>, false>>,
  Expect<Equal<Integer.GreatEq<2, 0>, true>>,
  Expect<Equal<Integer.GreatEq<0, 3>, false>>,
  Expect<Equal<Integer.GreatEq<0, -3>, true>>,
  Expect<Equal<Integer.GreatEq<0, 0>, true>>,
  Expect<Equal<Integer.GreatEq<2, 2>, true>>,
  Expect<Equal<Integer.GreatEq<-2, -2>, true>>,

  // Integer.Neq
  Expect<Equal<Integer.Neq<2, 1>, true>>,
  Expect<Equal<Integer.Neq<1, 2>, true>>,
  Expect<Equal<Integer.Neq<2, -1>, true>>,
  Expect<Equal<Integer.Neq<-1, 2>, true>>,
  Expect<Equal<Integer.Neq<-3, -2>, true>>,
  Expect<Equal<Integer.Neq<-2, -3>, true>>,
  Expect<Equal<Integer.Neq<-1, 0>, true>>,
  Expect<Equal<Integer.Neq<2, 0>, true>>,
  Expect<Equal<Integer.Neq<0, 3>, true>>,
  Expect<Equal<Integer.Neq<0, -3>, true>>,
  Expect<Equal<Integer.Neq<0, 0>, false>>,
  Expect<Equal<Integer.Neq<2, 2>, false>>,
  Expect<Equal<Integer.Neq<-2, -2>, false>>,

  // Integer.LessEq
  Expect<Equal<Integer.LessEq<2, 1>, false>>,
  Expect<Equal<Integer.LessEq<1, 2>, true>>,
  Expect<Equal<Integer.LessEq<2, -1>, false>>,
  Expect<Equal<Integer.LessEq<-1, 2>, true>>,
  Expect<Equal<Integer.LessEq<-3, -2>, true>>,
  Expect<Equal<Integer.LessEq<-2, -3>, false>>,
  Expect<Equal<Integer.LessEq<-1, 0>, true>>,
  Expect<Equal<Integer.LessEq<2, 0>, false>>,
  Expect<Equal<Integer.LessEq<0, 3>, true>>,
  Expect<Equal<Integer.LessEq<0, -3>, false>>,
  Expect<Equal<Integer.LessEq<0, 0>, true>>,
  Expect<Equal<Integer.LessEq<2, 2>, true>>,
  Expect<Equal<Integer.LessEq<-2, -2>, true>>,

  // Integer.Eq
  Expect<Equal<Integer.Eq<2, 1>, false>>,
  Expect<Equal<Integer.Eq<1, 2>, false>>,
  Expect<Equal<Integer.Eq<2, -1>, false>>,
  Expect<Equal<Integer.Eq<-1, 2>, false>>,
  Expect<Equal<Integer.Eq<-3, -2>, false>>,
  Expect<Equal<Integer.Eq<-2, -3>, false>>,
  Expect<Equal<Integer.Eq<-1, 0>, false>>,
  Expect<Equal<Integer.Eq<2, 0>, false>>,
  Expect<Equal<Integer.Eq<0, 3>, false>>,
  Expect<Equal<Integer.Eq<0, -3>, false>>,
  Expect<Equal<Integer.Eq<0, 0>, true>>,
  Expect<Equal<Integer.Eq<2, 2>, true>>,
  Expect<Equal<Integer.Eq<-2, -2>, true>>,

  // Integer.Dec
  Expect<Equal<Integer.Dec<2>, 1>>,
  Expect<Equal<Integer.Dec<0>, -1>>,
  Expect<Equal<Integer.Dec<1>, 0>>,
  Expect<Equal<Integer.Dec<-3>, -4>>,

]
