///////////////////////////////////////////////////////////////////
//                                                               //
// This Array test file is auto-generated by "script/lib-gen.sh" //
//                                                               //
///////////////////////////////////////////////////////////////////

import Array from "../lib/Array";
import { Equal, Expect } from "../utils";

type CaseLibArray = [
  // Array.Concat
  Expect<Equal<Array.Concat<[1,2,3], [2,3,1]>, [1,2,3,2,3,1]>>,

  // Array.CreateArrayFromLength
  Expect<Equal<Array.CreateArrayFromLength<2>, [undefined,undefined]>>,
  Expect<Equal<Array.CreateArrayFromLength<3, string>, [string,string,string]>>,
  Expect<Equal<Array.CreateArrayFromLength<0>, []>>,
  Expect<Equal<Array.CreateArrayFromLength<-1>, []>>,

  // Array.At
  Expect<Equal<Array.At<[1,2,3], 2>, 3>>,
  Expect<Equal<Array.At<[1,2,3,4], 0>, 1>>,

]
