/////////////////////////////////////////////////////////////////////
//                                                                 //
// This Boolean test file is auto-generated by "script/lib-gen.sh" //
//                                                                 //
/////////////////////////////////////////////////////////////////////

import Boolean from "../lib/Boolean";
import { Equal, Expect } from "../utils";

type CaseLibBoolean = [
  // Boolean.Nand
  Expect<Equal<Boolean.Nand<false, false>, true>>,
  Expect<Equal<Boolean.Nand<false, true>, true>>,
  Expect<Equal<Boolean.Nand<true, false>, true>>,
  Expect<Equal<Boolean.Nand<true, true>, false>>,

  // Boolean.MultipleAnd
  Expect<Equal<Boolean.MultipleAnd<[true,true,true]>, true>>,
  Expect<Equal<Boolean.MultipleAnd<[true,false,true]>, false>>,
  Expect<Equal<Boolean.MultipleAnd<[false,false,false]>, false>>,

  // Boolean.And
  Expect<Equal<Boolean.And<false, false>, false>>,
  Expect<Equal<Boolean.And<false, true>, false>>,
  Expect<Equal<Boolean.And<true, false>, false>>,
  Expect<Equal<Boolean.And<true, true>, true>>,

  // Boolean.Not
  Expect<Equal<Boolean.Not<false>, true>>,
  Expect<Equal<Boolean.Not<true>, false>>,

  // Boolean.Nor
  Expect<Equal<Boolean.Nor<false, false>, true>>,
  Expect<Equal<Boolean.Nor<false, true>, false>>,
  Expect<Equal<Boolean.Nor<true, false>, false>>,
  Expect<Equal<Boolean.Nor<true, true>, false>>,

  // Boolean.MultipleOr
  Expect<Equal<Boolean.MultipleOr<[true,true,true]>, true>>,
  Expect<Equal<Boolean.MultipleOr<[true,false,false]>, true>>,
  Expect<Equal<Boolean.MultipleOr<[false,false,false]>, false>>,

  // Boolean.Or
  Expect<Equal<Boolean.Or<false, false>, false>>,
  Expect<Equal<Boolean.Or<false, true>, true>>,
  Expect<Equal<Boolean.Or<true, false>, true>>,
  Expect<Equal<Boolean.Or<true, true>, true>>,

]
