////////////////////////////////////////////////////////////////////////
//                                                                    //
// This BigInteger test file is auto-generated by "script/lib-gen.sh" //
//                                                                    //
////////////////////////////////////////////////////////////////////////

import BigInteger from "../lib/BigInteger";
import { Equal, Expect } from "../utils";

type CaseLibBigInteger = [
  // BigInteger.Lower
  Expect<Equal<BigInteger.Lower<23, 123>, true>>,

]
