/////////////////////////////////////////////////////////////////////
//                                                                 //
// This Integer test file is auto-generated by "script/lib-gen.sh" //
//                                                                 //
/////////////////////////////////////////////////////////////////////

import Integer from "../lib/Integer";
import { Equal, Expect } from "../utils";

type CaseLibInteger = [
  // Integer.Mod
  Expect<Equal<Integer.Mod<2, 2>, 0>>,
  Expect<Equal<Integer.Mod<3, 2>, 1>>,
  Expect<Equal<Integer.Mod<-3, -2>, 1>>,
  Expect<Equal<Integer.Mod<-3, 2>, -1>>,
  Expect<Equal<Integer.Mod<9, 5>, 4>>,

  // Integer.Greater
  Expect<Equal<Integer.Greater<2, 1>, true>>,
  Expect<Equal<Integer.Greater<1, 2>, false>>,
  Expect<Equal<Integer.Greater<2, -1>, true>>,
  Expect<Equal<Integer.Greater<-1, 2>, false>>,
  Expect<Equal<Integer.Greater<-3, -2>, false>>,
  Expect<Equal<Integer.Greater<-2, -3>, true>>,
  Expect<Equal<Integer.Greater<-1, 0>, false>>,
  Expect<Equal<Integer.Greater<2, 0>, true>>,
  Expect<Equal<Integer.Greater<0, 3>, false>>,
  Expect<Equal<Integer.Greater<0, -3>, true>>,
  Expect<Equal<Integer.Greater<0, 0>, false>>,
  Expect<Equal<Integer.Greater<2, 2>, false>>,
  Expect<Equal<Integer.Greater<-2, -2>, false>>,

  // Integer.Add
  Expect<Equal<Integer.Add<2, 3>, 5>>,
  Expect<Equal<Integer.Add<-2, 2>, 0>>,
  Expect<Equal<Integer.Add<-2, -6>, -8>>,
  Expect<Equal<Integer.Add<3, -3>, 0>>,
  Expect<Equal<Integer.Add<3, -2>, 1>>,
  Expect<Equal<Integer.Add<-2, 1>, -1>>,
  Expect<Equal<Integer.Add<0, 0>, 0>>,
  Expect<Equal<Integer.Add<-2, 0>, -2>>,
  Expect<Equal<Integer.Add<2, 0>, 2>>,
  Expect<Equal<Integer.Add<0, 20>, 20>>,
  Expect<Equal<Integer.Add<0, -30>, -30>>,

  // Integer.IsPositive
  Expect<Equal<Integer.IsPositive<-2>, false>>,
  Expect<Equal<Integer.IsPositive<0>, false>>,
  Expect<Equal<Integer.IsPositive<9>, true>>,

  // Integer.IsOdd
  Expect<Equal<Integer.IsOdd<1>, true>>,
  Expect<Equal<Integer.IsOdd<2>, false>>,
  Expect<Equal<Integer.IsOdd<0>, false>>,
  Expect<Equal<Integer.IsOdd<-3>, true>>,
  Expect<Equal<Integer.IsOdd<-19>, true>>,
  Expect<Equal<Integer.IsOdd<20>, false>>,

  // Integer.IsNegative
  Expect<Equal<Integer.IsNegative<-2>, true>>,
  Expect<Equal<Integer.IsNegative<0>, false>>,
  Expect<Equal<Integer.IsNegative<9>, false>>,

  // Integer.IsZero
  Expect<Equal<Integer.IsZero<-2>, false>>,
  Expect<Equal<Integer.IsZero<0>, true>>,
  Expect<Equal<Integer.IsZero<9>, false>>,

  // Integer.Sub
  Expect<Equal<Integer.Sub<2, 3>, -1>>,
  Expect<Equal<Integer.Sub<3, 2>, 1>>,
  Expect<Equal<Integer.Sub<-2, 3>, -5>>,
  Expect<Equal<Integer.Sub<-2, -3>, 1>>,
  Expect<Equal<Integer.Sub<-9, -2>, -7>>,
  Expect<Equal<Integer.Sub<2, 0>, 2>>,
  Expect<Equal<Integer.Sub<-3, 0>, -3>>,
  Expect<Equal<Integer.Sub<0, 2>, -2>>,
  Expect<Equal<Integer.Sub<0, -3>, 3>>,
  Expect<Equal<Integer.Sub<0, 0>, 0>>,
  Expect<Equal<Integer.Sub<2, 2>, 0>>,
  Expect<Equal<Integer.Sub<-3, -3>, 0>>,

  // Integer.Opposite
  Expect<Equal<Integer.Opposite<-2>, 2>>,
  Expect<Equal<Integer.Opposite<0>, 0>>,
  Expect<Equal<Integer.Opposite<20>, -20>>,

  // Integer.Inc
  Expect<Equal<Integer.Inc<2>, 3>>,
  Expect<Equal<Integer.Inc<0>, 1>>,
  Expect<Equal<Integer.Inc<-1>, 0>>,
  Expect<Equal<Integer.Inc<-30>, -29>>,

  // Integer.Neq
  Expect<Equal<Integer.Neq<2, 1>, true>>,
  Expect<Equal<Integer.Neq<1, 2>, true>>,
  Expect<Equal<Integer.Neq<2, -1>, true>>,
  Expect<Equal<Integer.Neq<-1, 2>, true>>,
  Expect<Equal<Integer.Neq<-3, -2>, true>>,
  Expect<Equal<Integer.Neq<-2, -3>, true>>,
  Expect<Equal<Integer.Neq<-1, 0>, true>>,
  Expect<Equal<Integer.Neq<2, 0>, true>>,
  Expect<Equal<Integer.Neq<0, 3>, true>>,
  Expect<Equal<Integer.Neq<0, -3>, true>>,
  Expect<Equal<Integer.Neq<0, 0>, false>>,
  Expect<Equal<Integer.Neq<2, 2>, false>>,
  Expect<Equal<Integer.Neq<-2, -2>, false>>,

  // Integer.Eq
  Expect<Equal<Integer.Eq<2, 1>, false>>,
  Expect<Equal<Integer.Eq<1, 2>, false>>,
  Expect<Equal<Integer.Eq<2, -1>, false>>,
  Expect<Equal<Integer.Eq<-1, 2>, false>>,
  Expect<Equal<Integer.Eq<-3, -2>, false>>,
  Expect<Equal<Integer.Eq<-2, -3>, false>>,
  Expect<Equal<Integer.Eq<-1, 0>, false>>,
  Expect<Equal<Integer.Eq<2, 0>, false>>,
  Expect<Equal<Integer.Eq<0, 3>, false>>,
  Expect<Equal<Integer.Eq<0, -3>, false>>,
  Expect<Equal<Integer.Eq<0, 0>, true>>,
  Expect<Equal<Integer.Eq<2, 2>, true>>,
  Expect<Equal<Integer.Eq<-2, -2>, true>>,

  // Integer.GreaterEq
  Expect<Equal<Integer.GreaterEq<2, 1>, true>>,
  Expect<Equal<Integer.GreaterEq<1, 2>, false>>,
  Expect<Equal<Integer.GreaterEq<2, -1>, true>>,
  Expect<Equal<Integer.GreaterEq<-1, 2>, false>>,
  Expect<Equal<Integer.GreaterEq<-3, -2>, false>>,
  Expect<Equal<Integer.GreaterEq<-2, -3>, true>>,
  Expect<Equal<Integer.GreaterEq<-1, 0>, false>>,
  Expect<Equal<Integer.GreaterEq<2, 0>, true>>,
  Expect<Equal<Integer.GreaterEq<0, 3>, false>>,
  Expect<Equal<Integer.GreaterEq<0, -3>, true>>,
  Expect<Equal<Integer.GreaterEq<0, 0>, true>>,
  Expect<Equal<Integer.GreaterEq<2, 2>, true>>,
  Expect<Equal<Integer.GreaterEq<-2, -2>, true>>,

  // Integer.Divide
  Expect<Equal<Integer.Divide<2, 3>, 0>>,
  Expect<Equal<Integer.Divide<4, 2>, 2>>,
  Expect<Equal<Integer.Divide<9, -3>, -3>>,
  Expect<Equal<Integer.Divide<9, -2>, -4>>,
  Expect<Equal<Integer.Divide<9, 0>, never>>,
  Expect<Equal<Integer.Divide<-2, -3>, 0>>,
  Expect<Equal<Integer.Divide<-4, 2>, -2>>,
  Expect<Equal<Integer.Divide<4, 4>, 1>>,
  Expect<Equal<Integer.Divide<4, -4>, -1>>,
  Expect<Equal<Integer.Divide<-4, -4>, 1>>,

  // Integer.LowerEq
  Expect<Equal<Integer.LowerEq<2, 1>, false>>,
  Expect<Equal<Integer.LowerEq<1, 2>, true>>,
  Expect<Equal<Integer.LowerEq<2, -1>, false>>,
  Expect<Equal<Integer.LowerEq<-1, 2>, true>>,
  Expect<Equal<Integer.LowerEq<-3, -2>, true>>,
  Expect<Equal<Integer.LowerEq<-2, -3>, false>>,
  Expect<Equal<Integer.LowerEq<-1, 0>, true>>,
  Expect<Equal<Integer.LowerEq<2, 0>, false>>,
  Expect<Equal<Integer.LowerEq<0, 3>, true>>,
  Expect<Equal<Integer.LowerEq<0, -3>, false>>,
  Expect<Equal<Integer.LowerEq<0, 0>, true>>,
  Expect<Equal<Integer.LowerEq<2, 2>, true>>,
  Expect<Equal<Integer.LowerEq<-2, -2>, true>>,

  // Integer.IsEven
  Expect<Equal<Integer.IsEven<1>, false>>,
  Expect<Equal<Integer.IsEven<0>, true>>,
  Expect<Equal<Integer.IsEven<-22>, true>>,
  Expect<Equal<Integer.IsEven<19>, false>>,

  // Integer.Lower
  Expect<Equal<Integer.Lower<2, 1>, false>>,
  Expect<Equal<Integer.Lower<1, 2>, true>>,
  Expect<Equal<Integer.Lower<2, -1>, false>>,
  Expect<Equal<Integer.Lower<-1, 2>, true>>,
  Expect<Equal<Integer.Lower<-3, -2>, true>>,
  Expect<Equal<Integer.Lower<-2, -3>, false>>,
  Expect<Equal<Integer.Lower<-1, 0>, true>>,
  Expect<Equal<Integer.Lower<2, 0>, false>>,
  Expect<Equal<Integer.Lower<0, 3>, true>>,
  Expect<Equal<Integer.Lower<0, -3>, false>>,
  Expect<Equal<Integer.Lower<0, 0>, false>>,
  Expect<Equal<Integer.Lower<2, 2>, false>>,
  Expect<Equal<Integer.Lower<-2, -2>, false>>,

  // Integer.Dec
  Expect<Equal<Integer.Dec<2>, 1>>,
  Expect<Equal<Integer.Dec<0>, -1>>,
  Expect<Equal<Integer.Dec<1>, 0>>,
  Expect<Equal<Integer.Dec<-3>, -4>>,

]
