////////////////////////////////////////////////////////////////////
//                                                                //
// This String test file is auto-generated by "script/lib-gen.sh" //
//                                                                //
////////////////////////////////////////////////////////////////////

import String from "../lib/String";
import { Equal, Expect } from "../utils";

type CaseLibString = [
  // String.Length
  Expect<Equal<String.Length<"abs">, 3>>,
  Expect<Equal<String.Length<"">, 0>>,
  Expect<Equal<String.Length<"2222_2222_2222_2222_2222">, 24>>,

]
